### ISSUE TITLE
Testing Umbrella Issue - Hacktoberfest

### ISSUE THREAD

**Issue by PaulieScanlon** [PaulieScanlon/mdx-embed#71]
# ⛱️ Testing Umbrella Issue - Hacktoberfest

The time is right. We're now on to the last leg of the migration and something i never got round to in the [old repo](https://github.com/PaulieScanlon/gatsby-mdx-embed) was adding a test suite.

## 🚀 Getting Started

If you're interested in helping out with tests and taking part in [Hacktoberfest](https://hacktoberfest.digitalocean.com/) please comment below and let us know if it's the unit or integration test you'd like to tackle.

We'll then assign your username/name next to the component in the list below to try and avoid duplication. 
Once a PR has been created we'll then be able to assign you to the actual issue which should then appear in your Hacktoberfest contributions

## 🤝 Contributing

Before you start:
- Read the [CONTRIBUTING](https://github.com/PaulieScanlon/mdx-embed/blob/main/CONTRIBUTING.md#testing-wip).md
- Watch [MDX Embed - Hacktoberfest overview](https://www.youtube.com/watch?v=TzWm_tullLo)

## 🎁 As a thank you 

We know it's not much but if you would like to contribute and your PR is successfully merged we'll send you out a super cool limited edition MDX Embed sticker. If you're comfortable sharing your address you can email me pauliescanlon@gmail.com

## 🧪 The two tests 

There's two different types of tests we'd like contributors to focus on, they are at the moment fairly simple tests. There is every chance contributors with more expertise in testing will advise on what should or shouldn't be tested. 

I'm open to suggestions but at the very least each component will have the below which will get us to a stable `1.0.0` release

- Unit test (Testing Library / React)
- Integration test (Cypress)

## ❗ Issues 

There's an issue for each component and named appropriately: e.g: Please check the [issues](https://github.com/PaulieScanlon/mdx-embed/issues) in GitHub to see which tests are currently open or in progress

- `codepen-unit-test`
- `codepen-integration-test`

Each issue will be assigned the "Hacktoberfest" and perhaps the "good first issue" label?

### Unit Test 

_Unit tests are co-located e.g: `packages/mdx-embed/src/components/codepen.test.tsx`_
... and here's a brief explanation of how we're writing [unit tests](https://github.com/PaulieScanlon/mdx-embed/blob/main/CONTRIBUTING.md#unit-testing)

- It will have a `data-testid` that is the name of the component e.g: `data-testid="codepen"` - observe directory name for clues on what the `data-testid` should be
- It will have a `data-testid` attribute on the top level DOM node or iframe
- it will have at least one test for `it renders the component`
- It will have the correct file extension for the test file: e.g  `.test.tsx`

### Integration Test

_Integration tests are located at `cypress/integration/codepen.spec.js`_
... and here's a brief explanation about how we're currently writing [integration tests](https://github.com/PaulieScanlon/mdx-embed/blob/main/CONTRIBUTING.md#integration-tests)

- it will have at least one test which asserts if embed providers specific DOM are **not** undefined
- It will have the correct file extension for the test file: e.g `.spec.js`

## Unit Test Assignment List 👩‍💻👨‍💻

- [x] Airtable - @yenly
- [x] Buzzsprout - @matiasfha
- [x] Cinnamon - @xmalinov
- [x] CodePen - @PaulieScanlon 
- [x] CodeSandbox -@xmalinov
- [x] Egghead - @matiasfha
- [x] Flickr - @xmalinov
- [x] Gist - @remiroyc
- [x] GeneralObserver - @PaulieScanlon 
- [x] Instagram - @xmalinov
- [x] Lbry - @spences10
- [x] MDXEmbedProvider -  @PaulieScanlon
- [x] Pinterest - @kriswep
- [x] Simplecast - @spences10 
- [x] SoundCloud - @yenly 
- [x] Spotify - @remiroyc
- [x] Strava - @tricinel
- [x] TikTok - @kriswep
- [x] Twitch - @ekafyi
- [x] Twitter - @ekafyi
- [x] Vimeo - @tricinel
- [x] Whimsical - @kriswep
- [x] Wikipedia - @remiroyc
- [x] YouTube - ~~@remiroyc~~ @PaulieScanlon 

## Integration Test  Assignment List 👩‍💻👨‍💻

- [x] Airtable - @yenly
- [x] Buzzsprout - @matiasfha
- [x] Cinnamon - @tricinel
- [x] CodePen - @PaulieScanlon 
- [x] CodeSandbox - @matiasfha
- [x] Egghead - @matiasfha
- [x] Flickr - @tricinel
- [x] Gist - @matiasfha
- [x] Instagram - ~~@matiasfha~~ @PaulieScanlon 
- [x] Lbry - @spences10
- [x] Pinterest - @matiasfha
- [x] Simplecast - @spences10
- [x] SoundCloud - @yenly 
- [x] Spotify - @matiasfha
- [x] Strava - @tricinel
- [x] TikTok - @tricinel
- [x] Twitch - @yenly
- [x] Twitter - @PaulieScanlon  
- [x] Vimeo - @JeffersonBledsoe 
- [x] Whimsical - @tricinel
- [x] Wikipedia - @yenly
- [x] YouTube - @JeffersonBledsoe 

#### 😅 Phew ---- all tasks complete

- [x] Add jest - @PaulieScanlon 
- [x] Add Testing Library / React - @PaulieScanlon 
- [x] Add test for `GeneralObserver` - @PaulieScanlon 
- [x] Add Circle CI integration @PaulieScanlon 
- [x] Add cool badge to Repo with test status and coverage - @PaulieScanlon 
- [x] Write all the testing issues and label them #Hacktoberfest - @PaulieScanlon 
- [x] Recording of **MDX Embed - Hacktoberfest overview** - @PaulieScanlon & @spences10  [#79]

**Comment by PaulieScanlon** [comment]
testing suite merged in [#72 ]

**Comment by PaulieScanlon** [comment]
Test suite is now in place but the following components will all needs tests at some point:



## Component List

- [ ] Airtable
- [ ] Buzzprout
- [x] CodePen
- [ ] CodeSandbox
- [ ] Egghead
- [ ] Flickr
- [ ] Gist
- [ ] Instagram
- [ ] Lbry
- [ ] Pinterest
- [ ] Simplecast
- [ ] SoundCloud
- [ ] Spotify
- [ ] Strava
- [ ] TikTok
- [ ] Twitch
- [ ] Twitter
- [ ] Vimeo
- [ ] Wikipedia
- [ ] YouTube

**Comment by PaulieScanlon** [comment]
I've hit a bit of a road block using Jest and Testing Library and whilst i think we can have a unit test for each of the above It doesn't really fully test the component. 

The "real" test is that all of the props and bits we've introduced will always be properly passed on and a 3rd party embedded able widget will be rendered in the DOM. 

It's looking like it's not going to be possible to write a unit test to await the response of an embed script to then assert if e.g an iframe has the correct CodePen stuff in it but what might be better solution is integration testing with [cypress](https://vimeo.com/237527670) 

There's an interesting article [here](https://medium.com/@mtiller/testing-react-components-using-storybook-and-cypress-1689a27f55aa) explaining how to set it up as though Storybook is the "app"

I'm thinking we should probably have both unit tests and integration tests which "should" make all the components bulletproof... trouble is i haven't used Cypress before.... another thing to learn 🙄

**Comment by PaulieScanlon** [comment]
Just spilling my mind a bit in preparation for creating multiple issues for [Hacktoberfest](https://hacktoberfest.digitalocean.com/)

There's two different types of tests we'd like contributors to focus on, they are at the moment fairly simple tests. There is every chance contributors with more expertise in testing will advise on what should or shouldn't be tested. 

I'm open to suggestions but at the very least each component will have the below which will get us to a stable `1.0.0` release

## Issues 

There'll be an issue opened for each component and named appropriately: e.g:

- `codepen-unit-test`
- `codepen-integration-test`

Each issue will be assigned the "hacktoberfest" and perhaps the "good first issue" label?

## The two tests

- Unit tests (Testing Library / React)
- Integration tests (Cypress)

## Acceptance Criteria

**Unit Tests**
_Unit tests are co-located e.g: `packages/mdx-embed/src/components/codepen.test.tsx`_

- It will have a `data-testid` that is the name of the component e.g: `data-testid="codepen"` - observe directory name for clues on what the `data-testid` should be
- It will have a `data-testid` attribute on the top level DOM node or iframe
- it will have at least one test for `it renders the component`
- It will have the correct file extension for the test file: e.g  `.test.tsx`


**Integration Tests**
_Integration tests are located at `cypress/integration/codepen.spec.js`_

- it will have at least one test which asserts if embed providers specific DOM are **not** undefined
- It will have the correct file extension for the test file: e.g `.spec.js`

@spences10 thoughts welcome

**Comment by remiroyc** [comment]
Hello 👋  can you assign me to the Wikipedia #127, Youtube #129, Gist #103, and Spotify #115 (unit tests) issues.

**Comment by PaulieScanlon** [comment]
Hey @remiroyc I've added your name next to the components above! Thanks again for getting involved!

**Comment by matiasfha** [comment]
I can take the buzzsprout and egghead ones

**Comment by PaulieScanlon** [comment]
Hey @matiasfha I've added your name next to the components above in the Unit Test assignment list

Thanks again for getting involved!

**Comment by JeffersonBledsoe** [comment]
Hey @PaulieScanlon, any chance I can work on the [YouTube](https://github.com/PaulieScanlon/mdx-embed/issues/130) and [Vimeo](https://github.com/PaulieScanlon/mdx-embed/issues/126) integration tests? Maybe the [Twitter](https://github.com/PaulieScanlon/mdx-embed/issues/124) integration tests too?

I'm also happy to work on unit tests for those if they don't get picked up 🙂

**Comment by PaulieScanlon** [comment]
Hey @JeffersonBledsoe you absolutely can! I'll assign you to the integration tests for now and if you feel like taking on the Unit Tests too please comment again and i'll add your name to the list.

Welcome aboard and thanks from all of us!

**Comment by matiasfha** [comment]
I forgot to say I also want to take care of the integration tests for egghead and buzzsprout component (already did xD).
Also. go ahead and shoot me with anything else I can help @PaulieScanlon @spences10 happy to help you a bit more.

**Comment by xmalinov** [comment]
Hi @PaulieScanlon
Can you assign me to:
- [cinnamon-unit-test #91](https://github.com/PaulieScanlon/mdx-embed/issues/91)
- [codesandbox-unit-test #97](https://github.com/PaulieScanlon/mdx-embed/issues/97)
- [flickr-unit-test #101](https://github.com/PaulieScanlon/mdx-embed/issues/101)
- [instagram-unit-test #105](https://github.com/PaulieScanlon/mdx-embed/issues/105)

**Comment by PaulieScanlon** [comment]
Hey @xmalinov and welcome aboard! You sure can and i've added you name next to the components above.
Whenever you're ready create a PR and i'll assign the Hacktoberfest label to it.

Thanks for getting involved and please reach out if you have any questions or suggestions!

**Comment by spences10** [comment]
Hey @xmalinov thanks for getting involved, could I ask that you maybe pick one to start with then the other issues aren't restricted for other potential contributors?

If no one else want's to pick them you can pick them up after you have completed the current one you're working on?

**Comment by xmalinov** [comment]
@spences10 noprob, lets start from the cinnamon test

**Comment by xmalinov** [comment]
@PaulieScanlon @spences10 by the way, unit tests only for presence an iframe with certain id is the bad testing scenario. The iframe can be even with wrong props (tried to check it on spotify). There is only one way to check it - like it was done in buzzsprout tests (by checking props format and types by regexps)

**Comment by PaulieScanlon** [comment]
@matiasfha Excellent point. I'm not sure there's much we can do other testing for a string. But i do wonder if this is on the user rather than the component. Our integration tests will pick up if when a correct an id is passed via a prop the provider component will load and display but the unit test is really just to ensure that the General Observer puts the child in the dom. It's a tricky situation since so much of if these component. work on or is actually on the providers rather than us but we would like some kind of unit tests in there to catch any small issues.

The Buzzspout string test might be better placed in util somewhere maybe? There's a change other components will use this method... what do you think?

**Comment by spences10** [comment]
> @PaulieScanlon @spences10 by the way, unit tests only for presence an iframe with certain id is the bad testing scenario. The iframe can be even with wrong props (tried to check it on spotify). There is only one way to check it - like it was done in buzzsprout tests (by checking props format and types by regexps)

Ok, cool! This is good to know, so take a look at the Buzzsprout PR for guidance @xmalinov?

Also, 
> @spences10 noprob, lets start from the cinnamon test

I'll backtrack on what I said, @PaulieScanlon's approach will be more flexible so feel free to claim the four you suggested @xmalinov 

Thanks

**Comment by ekafyi** [comment]
Hi @PaulieScanlon @spences10, may I have a go at **Twitter** and **Twitch unit tests** please?

**Comment by spences10** [comment]
Hey @ekafyi! 

Thanks for joining in! Yes please do!

When you create a PR @PaulieScanlon will assign the Hacktoberfest label to it 🎉

**Comment by matiasfha** [comment]
@PaulieScanlon I think that the regex thing in the buzzpsrout component can be generalized to some function/hook

like `useValidateId(regex, id)` and returns true or false where  `regex` is defined by the component and id is the id used by the component.. but!.. i still the same logic to shortcircuit the rendering so is not offering anything different to the component itself. Maybe add this type of logic to the `GeneralObserver` ? and shortcircuit there ?

**Comment by matiasfha** [comment]
btw. I already did 4 prs. I can take more if you need or leave it for someone else that want to join to hacktoberfest. let me know

**Comment by spences10** [comment]
> @PaulieScanlon I think that the regex thing in the buzzpsrout component can be generalized to some function/hook
> 
> like `useValidateId(regex, id)` and returns true or false where `regex` is defined by the component and id is the id used by the component.. but!.. i still the same logic to shortcircuit the rendering so is not offering anything different to the component itself. Maybe add this type of logic to the `GeneralObserver` ? and shortcircuit there ?

That's a great shout @matiasfha 🎉

@PaulieScanlon thoughts??

**Comment by matiasfha** [comment]
Maybe, we can add to the testing guidelines to add a prop check for each component and the related test?

**Comment by PaulieScanlon** [comment]
@matiasfha thanks for the feedback. I'm still not really sure if this kind of check is required. There's no way to check an id will work with any of the providers as they're just strings and i'm just kind of thinking about the usage. If a user puts in an id and nothing renders on the page they'd double check the id until it does. It'll never break their blog post if it's MDX as there's no type checking or errors. There is potential maybe to have the string check and if it errors we create a generic "error with id" alert message just so the usage isn't just an empty page but beyond that i'm not 100% sure it's needed.

With regard to the other props. This is something i have planned for future releases. The focus right now is getting at least one unit test created for each component. More granular tests will come along later. I had hoped at some point to write a url validator for each component which would check the formed url conforms to the provider specs but.... it's a big job.


To keep this moving though perhaps it's worth opening a new issue where can discuss a more mature testing strategy because i agree it would be great to have it but attempting to implement this now will perhaps confuse the Hacktoberfest milestone goals.

**Comment by taylorcjohnson** [comment]
Hi @PaulieScanlon - could I try out the Strava unit #117 and integration #118 tests? I'm trying to get more practice with testing in general, so I may or may not have questions. Feel free to go with another dev if you think that would be a problem!

**Comment by PaulieScanlon** [comment]
@taylorcjohnson Ahoy and welcome! You're 100% welcome to claim those, and don't worry about skill level we're all happy to help!

**Comment by matiasfha** [comment]
> To keep this moving though perhaps it's worth opening a new issue where we can discuss a more mature testing strategy because i agree it would be great to have it but attempting to implement this now will perhaps confuse the Hacktoberfest milestone goals.

That sounds good.. I would love to con tribute beyond this month with this project so.. Cound with me in that discussion.

Also if you need help or any other hacktoberfest participant just ping me👍

**Comment by yenly** [comment]
Hello @PaulieScanlon @spences10 I would like to work on Airtable unit and integration testing if that's ok.

**Comment by spences10** [comment]
> Hello @PaulieScanlon @spences10 I would like to work on Airtable unit and integration testing if that's ok.

Hey @yenly, I've added your name against the issues on here, @PaulieScanlon will check it off when the PR is accepted, thanks 🙏

**Comment by spences10** [comment]
Added unit test for Lbry with #162

**Comment by yenly** [comment]
@PaulieScanlon @spences10 I would like to work on SoundCloud unit and integration tests next. 🙂

**Comment by PaulieScanlon** [comment]
@yenly Hey, that would be brills. I've added your name to the components above!

**Comment by yencodes** [comment]
@PaulieScanlon @spences10 I would be happy to help out with more tests but don't want to take them from other Hacktoberfest participants for first good issues. I'm looking to contribute beyond Hacktoberfest so let me know if these doesn't get picked up. I will gladly help.

**Comment by yenly** [comment]
@PaulieScanlon @spences10 I would be happy to help out with more tests but don't want to take them from other Hacktoberfest participants for first good issues. I'm looking to contribute beyond Hacktoberfest so let me know if these don't get picked up. I will gladly help.

**Comment by PaulieScanlon** [comment]
Hey @yenly Thanks, i see no harm in doing more if you'd like too. We'd welcome the help and we are just about half way through Hacktoberfest and just about half way through the issues. We may re-assign some of the above issues soon enough as some that have been claimed remain open. Just deciding on how long or what notice we should give those who asked to take on the issue but haven't created PR's yet.

**Comment by matiasfha** [comment]
Hey @PaulieScanlon @spences10 feel free to assign me some of those issues if no one else (related to hacktoberfest) claims them. 
Free and glad to help!

**Comment by PaulieScanlon** [comment]
Thanks @matiasfha We're a little light on Integration Tests so if you'd like to take on a few of those that would be brills!

**Comment by matiasfha** [comment]
nice... Later tonight (my night xD) will push some prs for those. I will try to do as many as I can

**Comment by PaulieScanlon** [comment]
@matiasfha Thanks! Can you let me know which ones and i'll add your name to the list! Ty!

**Comment by matiasfha** [comment]
Let's say CodeSandbox, Gist, Instagram, Pinterest and Spotify. I think can do at least those today

**Comment by yenly** [comment]
I can take Twitch & Wikipedia integration tests.

**Comment by PaulieScanlon** [comment]
@matiasfha Lovely stuff! Thanks so much mate!

**Comment by PaulieScanlon** [comment]
@yenly super brill, brills. Thanks so much!

**Comment by kriswep** [comment]
Can i try the tiktok unit test? That seems to be not taken.

**Comment by PaulieScanlon** [comment]
Hey @kriswep, you absolutely can and welcome aboard 🚢 

I've added your name to the list above. Please do comment on the issue if you have any questions and one of us will get back to ya!

**Comment by tricinel** [comment]
Hey @PaulieScanlon, is Vimeo's unit tests still up for grabs? #125 :)

**Comment by kriswep** [comment]
Just added a PR for the tiktok unit test.
Could also make one for Pinterest unit tests, that seems to be unassigned.

**Comment by PaulieScanlon** [comment]
@kriswep Hey mate, i've added your name to the Pinterest unit test. Ty!

**Comment by PaulieScanlon** [comment]
@tricinel, Hey, Vimeo unit test is all yours! Let us know if you have any questions! Thanks for getting involved!

**Comment by kriswep** [comment]
Hey, I just send PR #188 with an unit test for whimsical.

**Comment by PaulieScanlon** [comment]
@remiroyc Just a friendly nudge. You claimed the YouTube Unit Test, would you still like to take this on. No worries if not we can remove your name from the list and allow other contributors the opportunity to claim it.

**Comment by PaulieScanlon** [comment]
@taylorcjohnson  Just a friendly nudge. You claimed the Strava Unit Test, would you still like to take this on. No worries if not we can remove your name from the list and allow other contributors the opportunity to claim it.

**Comment by tricinel** [comment]
@PaulieScanlon just wondering if any of the integration tests for:

- Cinnamon
- Flickr
- TikTok
- Whimsical

are under way? They look unassigned :) Would love to get my hands dirty with cypress a bit (it's a bit new to me, so could learn something 💯 ).

**Comment by PaulieScanlon** [comment]
Hey @tricinel Yeah 100% of course. I'll add your name to the list about. If you're new to Cypress (as we all are) you might be find the [CONTRIBUTING](https://github.com/PaulieScanlon/mdx-embed/blob/main/CONTRIBUTING.md#integration-tests) doc helpful. We also cover integration tests in the [overview](https://www.youtube.com/watch?v=TzWm_tullLo) video but do let me know if you run to any issues.

**Comment by tricinel** [comment]
Ok, great thank you! Thanks for the pointers on the resources as well. I'll take a look at everything before diving in today.

**Comment by tricinel** [comment]
@PaulieScanlon I do have a question regarding the integration tests. I may be doing something wrong, but I'm getting some false positives. For example, on the codepen.spec (https://github.com/PaulieScanlon/mdx-embed/blob/main/cypress/integration/codepen.spec.js#L9), just by changing that selector to something that doesn't exist on the page will still pass the test.

What am I missing?

![Screenshot 2020-10-20 at 12 55 35](https://user-images.githubusercontent.com/216008/96578753-3f9c5780-12c5-11eb-865b-970e73dcd73e.png)

**Comment by PaulieScanlon** [comment]
@tricinel Hmmm... that's interesting / alarming 😂 that test should definitely fail. I wonder if there's something funky going on in the `getIframeBody` function... that is a custom helper because Storybook runs in an iframe and it's quite difficult to get at the actual DOM node when it's not in the current window if that make sense. Maybe i need to look in to this. 

Feel free to keep working on it and perhaps create a PR and i'll take a look, totally fine if you wanna pause on this for now, sounds like it's our problem with the way we'v advised collaborators to write the integration tests.

**Comment by tricinel** [comment]
@PaulieScanlon I though maybe it was something I missed. No worries, I'm looking into it as well. Two pairs of eyes are better than one I guess ;) Appreciate the help and quick reply. Do let me know if you find the missing link and I'll do the same.

**Comment by tricinel** [comment]
@PaulieScanlon I think I got it working properly now. I might do the cinnamon spec tests and push to my fork for you to check it out. The tests look like this now:

![Screenshot 2020-10-20 at 19 31 06](https://user-images.githubusercontent.com/216008/96623012-37124400-12fa-11eb-8831-4711f2e163fe.png)

**Comment by tricinel** [comment]
@PaulieScanlon check this out: https://github.com/tricinel/mdx-embed/commit/1347e35f8beea6fbbe271113f48f1882987dce67. Adding this will probably break all existing integration tests (although I think they all or most gave false positives) - but the changes to make them work properly will be minimal. I've added a sanity test to check for false positives as well in the cinnamon spec.

With adding a cypress command as well, we don't need to import `getIframeBody` any more...it's available in the cy namespace.

What do you think?

**Comment by matiasfha** [comment]
I like the addition of a sanity check, maybe that can be added as a command too?
And at least to me the getIframeBody as command makes sense!.. Nice addition!.

@PaulieScanlon I can help you with checking the other integration to check that works with the change  @tricinel is proposing. (during the week)

**Comment by PaulieScanlon** [comment]
@tricinel This is a beaut! Excellent job! I also like the addition of the Cypress.command. Its kind of similar to one of the Jest utils we have so again super brills job! I guess the only tricky part now is how may CI tests will fail when we merge this in. 

As you say though it should be fairly minimal work to correct. We're not planning a new release for a little while anyway so it's not the end of the world if the tests are failing for a little while.

Would you like to create a PR and we'll see what happens 😬

Following that i'll assess what needs fixing up in the other tests and if you're cool to lend a hand @matiasfha we can work out a bit of a plan of attack.

How's that sound?

**Comment by matiasfha** [comment]
Sounds good to me!.

Ping me here or in Discord and we can plan something! Happy to help

**Comment by tricinel** [comment]
Yeah, sounds good to me. By the way, I did a find and replace in the integration folder for `getIframeBody` to replace with `cy.getIframeBody` and got 41 occurrences. Ran all the tests and got 1 failure, on airtable. I guess we're in a pretty good state.

I'll push in a sec.

**Comment by tricinel** [comment]
Pushed in #191

**Comment by taylorcjohnson** [comment]
> @taylorcjohnson Just a friendly nudge. You claimed the Strava Unit Test, would you still like to take this on. No worries if not we can remove your name from the list and allow other contributors the opportunity to claim it.

@PaulieScanlon Yes, apologies for the slow start, but I'd still like to take a crack at it. I can follow-up on Friday if I think I won't be able to help (to allow you to open it back up to other contributors).

**Comment by tricinel** [comment]
So then the integration tests for Cinnamon should be done now, so I'll move on to the ones for Flickr, TikTok and Whimsical. Cheers!

**Comment by PaulieScanlon** [comment]
@taylorcjohnson Hey mate, yeah that's totally fine. No real rush just wanted to check you'd still like to take it on. Ty for the response!

**Comment by yenly** [comment]
@PaulieScanlon Twitch player displays "player.twitch.tv refused to connect." when running storybook locally. It works on the deployed site --> https://www.mdx-embed.com/?path=/docs/components-twitch--usage
Not sure how to test when it renders error page in the iframe.

**Comment by PaulieScanlon** [comment]
Hey @yenly Thanks for looking into this. There's more information about this particular integration tests on [issue #122](https://github.com/PaulieScanlon/mdx-embed/issues/122)

**Comment by taylorcjohnson** [comment]
@PaulieScanlon Unfortunately, I won't be able to help with the Strava tests at the moment if you wanted to open it up to other contributors. Apologies - hope this doesn't cause any problems for you!

**Comment by tricinel** [comment]
I'll have a look at the Strava tests if no one else is up for it. 👍

**Comment by PaulieScanlon** [comment]
@taylorcjohnson thanks for letting me know, no worries at all! @tricinel if you're up for it then please go ahead. I'll add your name up top! Thanks!!!

**Comment by JeffersonBledsoe** [comment]
@PaulieScanlon Unfortunately I haven't found time & probably won't find any time soon to work on the Twitter integration tests (the local storyboard doesn't display as it does in the live storyboard). Feel free to unassign me so others can work on it :) If it doesn't get picked up again, I'll still try put some time in when I can!

**Comment by PaulieScanlon** [comment]
@JeffersonBledsoe hey mate, no problems at all. That Twitter one might be a little tricky. Perhaps i'll take that one on. Thanks for letting me know!

**Comment by PaulieScanlon** [comment]
Hey @remiroyc @tricinel @matiasfha Just a friendly nudge to see if you're still able to take on the tests above. No worries if not it's totally cool if you don't have capacity to do the work. We're hoping to have all tests completed by end of October so if you don't feel you'll have time could you let me know and i'll remove your name so others could potentially contribute.

Thanks in advance!

**Comment by tricinel** [comment]
Hey @PaulieScanlon, I'll take care of Strava today :)

**Comment by PaulieScanlon** [comment]
@tricinel lovely stuff! Thanks so much!!

**Comment by matiasfha** [comment]
@PaulieScanlon I have as WIP the pinterest one. I will work on this before EOW.

**Comment by PaulieScanlon** [comment]
@matiasfha thanks mate. I could take Instagram and Spotify off your hands if you like. We're keen to get this wrapped up today / tomorrow if possible.

**Comment by matiasfha** [comment]
@PaulieScanlon I just open the PR for pinterest.
I can take Spotify later today and whatever is available.

**Comment by PaulieScanlon** [comment]
@matiasfha Mega thanks mate! Both Spotify and Pinterest are approved and merged. Just Instagram to go now, but i'm happy to pick this up. 
You've done more than your fair share!

**Comment by PaulieScanlon** [comment]
Hello everyone, and Happy Halloween 🎃

As of 10.25 this morning (UK time) we have successfully closed 76 issues, and have reached an overall code coverage of 94% which is absolute brills considering we started with 0%

Myself, @spences10  and @molebox would like to thank you for all your hard word, your commitment to the cause and for all being so wonderful to collaborate with. I for one have really enjoyed this years Hacktoberfest and we hope you have too.

As mentioned above as a small thank you we do have a limited amount of MDX Embed stickers so if you're happy to share you address please email me pauliescanlon@gmail.com and i'll get a couple out in the post (mail) for you.

Work will continue on the repo and if any of you will like to contribute again keep an eye on the issues.

Excellent, excellent work everyone, and thanks again - we bloody did it! 🕺
